### PR TITLE
Set rails dependency down to ~> 5.2.0

### LINKED ISSUE #4: Support for Rails 5.2
Hey guys,

at first good to see things keep moving using the db as active storage backend after having a look on alternative projects. This looks like to the best version around.
Just one question, is there a reason why the gemspec requires rails 6.0? I'm just playing around a bit and it seems to work with 5.2, too. After setting rails and active storage to 5.2 there were no failures for the mysql specs. I haven't tested postgres. I will now go on and check if there are issues arising with 5.2 in development.

### PR DESCRIPTION
**Pull request by henkesn**
As I could not find any errors with rails 5.2 I suggest downgrading the minimum required version.

Fixes #4

### CODE REVIEW

**Comment by henkesn** [comment]
Let's see, what the specs do.

**Comment by blocknotes** [comment]
Hey @henkesn.
Sorry to reply so late.
I tried to downgrade as you propose (also updating `spec/dummy/config/application.rb`) but some tests fails.

```ruby
     Failure/Error: ActiveStorage::Blob.create_and_upload! io: StringIO.new(data), filename: filename, content_type: content_type, identify: identify, record: record # rubocop:disable Layout/LineLength

     NoMethodError:
       undefined method `create_and_upload!' for #<Class:0x00007fc80757f0e0>
       Did you mean?  create_after_upload!
```

**Comment by henkesn** [comment]
@blocknotes never mind. We had in running for some time in production with rails 5.2 without issues. During migration I noticed that the way I set it for rails 5 was wrong anyway as it won't accept rails 6 anymore. It would be better to use a version constraint like `'>= 5.2.0', '< 7'`.
But as already said, we have already migrated which probably makes it hard to maintain for 5.2.
I'd just leave it like it is and close this PR.
